### PR TITLE
Update goreleaser Homebrew configuration

### PR DESCRIPTION
**Pull request by duffn**
Some minor updates to the Homebrew configuration.

### CODE REVIEW

**Comment by duffn** [comment]
I'm not sure why this failed?

```
make ci-test
'make' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

**Comment by selfup** [comment]
I would amend the commit and have Travis CI run again. See if that'll do it 🚀

**Comment by duffn** [comment]
That did it, thanks.

**Comment by markbates** [comment]
@duffn any chance I get you to re-open this against the `.gorelease.yml.plush` template file instead? I can do it myself if you don't care about getting the credit for the commit.

**Pull request closed without merging**
